djangodelights/djangodelights/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
    path('inventory/', include('inventory.urls', namespace='inventory')),

]

djangodelights/inventory/urls.py
from django.urls import path, include

from .views import IndexView, InventoryView, CreateIngredientView, UpdateIngredientView, DeleteIngredientView, MenuView, PurchasesView, NewPurchaseView, ProfitView, RecipeView

from django.conf import settings
from django.conf.urls.static import static

app_name = 'inventory'

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('inventory/', InventoryView.as_view(), name='inventory'),
    path('add_ingredient/', CreateIngredientView.as_view(), name='add_ingredient'),
    path('edit_ingredient/<int:pk>/',
         UpdateIngredientView.as_view(), name='edit_ingredient'),
    path('inventory/<int:pk>/delete/',
         DeleteIngredientView.as_view(), name='delete_ingredient'),
    path('menu/', MenuView.as_view(), name='menu'),
    path('purchases/', PurchasesView.as_view(), name='purchases'),
    path('new_purchase/', NewPurchaseView.as_view(), name='new_purchase'),
    path('profit/', ProfitView.as_view(), name='profit'),
    path('recipe/', RecipeView.as_view(), name='recipe'),

]


# """Remember: In production, you should configure your web server to serve static files directly instead of relying on Django to serve them.
# # Nginx: In your Nginx configuration file, add the following lines:

# location /media/ {
#   alias /path/to/your/media/root/;
# }

# location /static/ {
#   alias /path/to/your/static/root/;
# }
# """
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

djangodelights/inventory/models.py
from django.db import models


# Create your models here.


class Ingredients(models.Model):
    ingredient = models.CharField(max_length=30)
    quantity = models.FloatField(default=0.0)
    unit = models.CharField(max_length=10)
    price_per_unit = models.FloatField(default=0.0)


class MenuItem(models.Model):
    title = models.CharField(max_length=30)
    price = models.FloatField(default=0.0)
    image = models.ImageField(upload_to='menu_images/', blank=True)
    recipe_url = models.URLField(blank=True)

    # return a string representation of the object
    def __str__(self):
        return self.title


class RecipeRequirement(models.Model):
    menu_item = models.ForeignKey(
        "inventory.MenuItem", on_delete=models.CASCADE)
    ingredient = models.ForeignKey(
        "inventory.Ingredients", on_delete=models.CASCADE)
    quantity = models.FloatField(default=0.0)


class Purchase(models.Model):
    menu_item = models.ForeignKey(MenuItem, on_delete=models.CASCADE)
    quantity = models.FloatField(default=0.0)
    timestamp = models.DateTimeField(auto_now_add=True)
    price = models.FloatField(default=0.0)

    def save(self, *args, **kwargs):
        ingredient = RecipeRequirement.objects.get(
            menu_item=self.menu_item).ingredient
        self.price = ingredient.price_per_unit
        self.purchase_total_price = self.price * self.quantity
        super().save(*args, **kwargs)

    @property
    def purchase_total_price(self):
        return self.price * self.quantity

djangodelights/inventory/forms.py
from django import forms
from .models import Ingredients, MenuItem, RecipeRequirement, Purchase

# CRUD - Create


class IngredientsCreateForm(forms.ModelForm):
    class Meta:
        model = Ingredients
        fields = ('ingredient', 'quantity', 'unit', 'price_per_unit')


class MenuItemCreateForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ('title', 'price')


class RecipeRequirementCreateForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = ('menu_item', 'ingredient', 'quantity')


class PurchaseCreateForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('menu_item', 'timestamp')

# CRUD - Update


class IngredientsUpdateForm(forms.ModelForm):
    class Meta:
        model = Ingredients
        fields = ('ingredient', 'quantity', 'unit', 'price_per_unit')


class MenuItemUpdateForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = ('title', 'price')


class RecipeRequirementUpdateForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = ('menu_item', 'ingredient', 'quantity')


class PurchaseUpdateForm(forms.ModelForm):
    class Meta:
        model = Purchase
        fields = ('menu_item', 'timestamp')

djangodelights/inventory/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from inventory.models import Ingredients, MenuItem, Purchase
from django.urls import reverse_lazy
# from inventory.views import HomeView, IngredientsView, NewIngredientView, UpdateIngredientView, MenuView, NewMenuItemView, PurchasesView, NewPurchaseView


# Create your views here.

# Find problems with the following code
class IndexView(TemplateView):
    template_name = 'home.html'


class InventoryView(ListView):
    model = Ingredients
    template_name = 'inventory.html'
    context_object_name = 'ingredients'


class CreateIngredientView(CreateView):
    model = Ingredients
    fields = '__all__'
    template_name = 'add_ingredient.html'
    success_url = reverse_lazy('inventory:index')


class UpdateIngredientView(UpdateView):
    model = Ingredients
    fields = ('ingredient', 'quantity')
    template_name = 'edit_ingredient.html'
    success_url = reverse_lazy('inventory')


class DeleteIngredientView(DeleteView):
    model = Ingredients
    success_url = reverse_lazy('inventory')
    template_name = 'ingredient_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ingredient'] = self.get_object()
        return context


class MenuView(ListView):
    model = MenuItem
    template_name = 'menu.html'
    context_object_name = 'menu_items'


class PurchasesView(ListView):
    template_name = "purchase_list.html"
    model = Purchase


class NewPurchaseView(CreateView):
    model = Purchase
    fields = '__all__'
    template_name = 'new_purchase.html'
    success_url = reverse_lazy('inventory:purchases')


class ProfitView(TemplateView):
    template_name = 'profit.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        purchases = Purchase.objects.all()
        menu_items = MenuItem.objects.all()

        revenue = 0
        cost = 0

        for purchase in purchases:
            revenue += purchase.total_price

        for menu_item in menu_items:
            cost += menu_item.price

        profit = revenue - cost
        context['revenue'] = revenue
        context['cost'] = cost
        context['profit'] = profit
        return context


class RecipeView(TemplateView):
    template_name = 'recipe.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_items'] = MenuItem.objects.all()
        return context

djangodelights/inventory/templates/add_ingredient.html
{% extends 'base.html' %}

{% block content %}
    <h1>Add Ingredient</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

djangodelights/inventory/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <title>Inventory App</title>
</head>
<body>
    <header class="navbar navbar-expand-lg navbar-light bg-light">
        <nav class="container">
            <a class="navbar-brand" href="{% url 'inventory:home' %}">Inventory App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'inventory:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'inventory:menu' %}">Menu</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'inventory:purchases' %}">Purchases</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container mt-5">
        {% block content %}{% endblock %}
    </main>
    <footer class="bg-light py-3">
        <div class="container">
            <p>Copyright © {{ current_year }} Inventory App</p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

djangodelights/inventory/templates/edit_ingredient.html
{% extends 'base.html' %}
{% block content %}
    <h1>Edit Ingredient</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
        <a href="{% url 'inventory:inventory' %}">Cancel</a>
    </form>
{% endblock %}

djangodelights/inventory/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center my-5">Welcome to Django Delights</h1>
    <p class="text-center">Here are some quick links to manage your restaurant:</p>
    <div class="d-flex justify-content-center">
        <ul class="list-group mb-5">
            <li class="list-group-item"><a href="{% url 'inventory:inventory' %}">Inventory</a></li>
            <li class="list-group-item"><a href="{% url 'inventory:menu' %}">Menu</a></li>
            <li class="list-group-item"><a href="{% url 'inventory:purchases' %}">Purchases</a></li>
            <li class="list-group-item"><a href="{% url 'inventory:profit' %}">Profit & Revenue</a></li>
        </ul>
    </div>
</div>
{% endblock %}

djangodelights/inventory/templates/ingredient_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <h1 class="text-center mt-5">Confirm Deletion</h1>
    <div class="row justify-content-center">
      <div class="col-lg-6 col-md-8 col-sm-12">
        <div class="card mt-5">
          <div class="card-body">
            <p>Are you sure you want to delete the ingredient "{{ ingredient.ingredient }}"?</p>
            <form action="{% url 'inventory:delete_ingredient' ingredient.id %}" method="post">
              {% csrf_token %}
              <input type="submit" value="Yes, Delete" class="btn btn-danger mr-3">
              <a href="{% url 'inventory:inventory' %}" class="btn btn-secondary">Cancel</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

djangodelights/inventory/templates/inventory.html
{% extends 'base.html' %}

{% block content %}
  <h1>Inventory</h1>
  <table>
    <thead>
      <tr>
        <th>Ingredient</th>
        <th>Quantity</th>
        <th>Unit</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for ingredient in ingredients %}
        <tr>
          <td>{{ ingredient.ingredient }}</td>
          <td>{{ ingredient.quantity }}</td>
          <td>{{ ingredient.unit }}</td>
          <td>
            <a href="{% url 'inventory:edit_ingredient' ingredient.id %}">Edit</a>
            <a href="{% url 'inventory:delete_ingredient' ingredient.id %}">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'inventory:add_ingredient' %}">Add Ingredient</a>
{% endblock %}

djangodelights/inventory/templates/inventory/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Inventory App</title>
</head>
<body>
    <header>
        <nav>
            <a href="{% url 'inventory:index' %}">Home</a>
            <a href="{% url 'inventory:menu' %}">Menu</a>
            <a href="{% url 'inventory:purchases' %}">Purchases</a>
            <a href="{% url 'inventory:ingredients' %}">Ingredients</a>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>Copyright © {{ current_year }} Inventory App</p>
    </footer>
</body>
</html>

djangodelights/inventory/templates/menu.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="text-center mb-5">Menu</h1>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Price</th>
          <th>Image</th>
          <th>Recipe URL</th>
        </tr>
      </thead>
      <tbody>
        {% for menu_item in menu_items %}
          <tr>
            <td>{{ menu_item.title }}</td>
            <td>{{ menu_item.price }}</td>
            <td>
              {% if menu_item.image %}
                <img src="{{ menu_item.image.url }}" height="50" width="50">
              {% endif %}
            </td>
            <td>
              {% if menu_item.recipe_url %}
                <a href="{{ menu_item.recipe_url }}">Link</a>
              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endblock %}

djangodelights/inventory/templates/profit.html
{% extends 'base.html' %}

{% block content %}
<h1>Profit and Revenue</h1>
<p>Total Revenue: {{ total_revenue }}</p>
<p>Total Cost: {{ total_cost }}</p>
<p>Profit: {{ profit }}</p>
{% endblock %}

djangodelights/inventory/templates/purchase_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Purchases</h1>

    <table>
        <thead>
            <tr>
                <th>Menu Item</th>
                <th>Timestamp</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in purchases %}
                <tr>
                    <td>{{ purchase.menu_item }}</td>
                    <td>{{ purchase.quantity }}</td>
                    <td>{{ purchase.timestamp }}</td>
                    <td>{{ purchase.purchase_total_price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

djangodelights/inventory/templates/purchases.html
{% extends "base.html" %}

{% block content %}
    <h1>Purchases</h1>

    <table>
        <thead>
            <tr>
                <th>Menu Item</th>
                <th>Timestamp</th>
                <th>Total Price</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in purchases %}
                <tr>
                    <td>{{ purchase.menu_item }}</td>
                    <td>{{ purchase.timestamp }}</td>
                    <td>{{ purchase.purchase_total_price }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}